### ISSUE TITLE
Composer overriders base/default/template

### ISSUE THREAD

**Issue by Razko90** [sveawebpay/magento1-checkout#3]
"app/design/frontend/base/default/template/",
are being overwritten by the composer install.

FIX:

`"magento-map-overwrite": {
      "sveaekonomi/magento1-checkout": [
        ["app/code/community/Svea/Checkout", "app/code/community/Svea/Checkout"],
        ["app/design/frontend/base/default/layout/sveacheckout.xml","app/design/frontend/base/default/layout/sveacheckout.xml"],
        ["app/design/adminhtml/default/default/layout/sveacheckout.xml","app/design/adminhtml/default/default/layout/sveacheckout.xml"],
        ["app/design/frontend/base/default/template/agreements.phtml","app/design/frontend/base/default/template/agreements.phtml"],
        ["app/design/frontend/base/default/template/sveacheckout.phtml","app/design/frontend/base/default/template/sveacheckout.phtml"],
        ["app/design/frontend/base/default/template/sveacheckout_snippet_renderer.phtml","app/design/frontend/base/default/template/sveacheckout_snippet_renderer.phtml"],
        ["app/design/frontend/base/default/template/sveacheckout","app/design/frontend/base/default/template/sveacheckout"],
        ["app/design/frontend/base/default/template/payment/form/sveacheckout.phtml","app/design/frontend/base/default/template/payment/form/sveacheckout.phtml"],
        ["app/design/adminhtml/default/default/template/sveacheckout/","app/design/adminhtml/default/default/template/sveacheckout/"],
        ["app/etc/modules/Svea_Checkout.xml","app/etc/modules/Svea_Checkout.xml"],
        ["js/Svea/Checkout/","js/Svea/Checkout/"],
        ["skin/frontend/base/default/css/sveacheckout/","skin/frontend/base/default/css/sveacheckout/"],
        ["skin/adminhtml/base/default/css/sveacheckout/","skin/adminhtml/base/default/css/sveacheckout/"]
      ]
    },
`

**Comment by TekniskSupport** [comment]
Thanks for your input, can you please make a pull-request from this?
It makes it easier to discuss the actual changes (or even see what changes are requested)

Another tip would be to make the json blob encapsulated in three backtics.
like this:
```json
"magento-map-overwrite": 
        {
     "sveaekonomi/magento1-checkout": [
            [
                "app/code/community/Svea/Checkout",
                "app/code/community/Svea/Checkout"
            ],
            [
                "app/design/frontend/base/default/layout/sveacheckout.xml",
                "app/design/frontend/base/default/layout/sveacheckout.xml"
            ],
            [
                "app/design/adminhtml/default/default/layout/sveacheckout.xml",
                "app/design/adminhtml/default/default/layout/sveacheckout.xml"
            ],
            [
                "app/design/frontend/base/default/template/",
                "app/design/frontend/base/default/template/"
            ],
            [
                "app/design/adminhtml/default/default/template/sveacheckout/",
                "app/design/adminhtml/default/default/template/sveacheckout/"
            ],
            [
                "app/etc/modules/Svea_Checkout.xml",
                "app/etc/modules/Svea_Checkout.xml"
            ],
            [
                "js/Svea/Checkout/",
                "js/Svea/Checkout/"
            ],
            [
                "skin/frontend/base/default/css/sveacheckout/",
                "skin/frontend/base/default/css/sveacheckout/"
            ],
            [
                "skin/adminhtml/base/default/css/sveacheckout/",
                "skin/adminhtml/base/default/css/sveacheckout/"
            ]
        ]
    }
}
```

**Comment by eagl3s1ght** [comment]
The problem is that when magento-deploy-strategy: symlink is used, the current greedy mapping replaces `app/design/frontend/base/default/template/` with a symlink to vendor/..
Thus, everything in `app/design/frontend/base/default/template/` of the magento installation is gone.

When one could argue that `magento-deploy-strategy: symlink` is not "supported by the module", another one could argue that it's not magento praxis to put template files directly into `app/design/frontend/base/default/template/` (just incase that discussion comes to show)
