### ISSUE TITLE
Checkout error on Magento 1.9.2.4

### ISSUE THREAD

**Issue by popduyhan** [sveawebpay/magento1-checkout#7]
Hi support team,

I have an error at the checkout page after installing your extension into our website.

Here is the error detail
![image](https://user-images.githubusercontent.com/6051682/66204174-73b1d400-e6d4-11e9-8593-ba5aa92715ef.png)

It shows that the controller sveacheckout/updateCart/updateCheckout/ can't be found.

Please help to solve it.

Thank you.

Regards,
Han.

**Comment by TekniskSupport** [comment]
Hi,

sveacheckout/updateCart/updateCheckout
Which should load this file 
`app/code/community/Svea/Checkout/controllers/UpdateCartController.php`
and run this method 
`updateCheckoutAction()`

The url is set in sveacheckout.phtml using this code:
`<?= Mage::getUrl('sveacheckout/updateCart/updateCheckout', array('_secure' => true)) ?>`

As sveacheckout/index/index seems to work my first guess would be that it has something to do with that the url has uppercase characters? Can your setup handle uppercase characters in urls?

Kind Regards
Iesus

**Comment by popduyhan** [comment]
Hi Lesus,

Thanks for your feedback.

I tried to do your suggestion but it doesn't work.

Regards,
Han.

**Comment by TekniskSupport** [comment]
Hi, 

I tested installing an 1.9.2.4 and tested the update myself, however unable to reproduce the error
What does your setup look like, which host operating system, what webserver and so on? 

![image](https://user-images.githubusercontent.com/13868526/66374753-fde78a00-e9ab-11e9-9fa3-f0c14dc6bfb5.png)

**Comment by popduyhan** [comment]
Hi,

I am using Ubuntu 18.04.3 LTS. Apache 2.4.29 and PHP 5.6.40.

I see some issues after updating the order info
![Selection_042](https://user-images.githubusercontent.com/6051682/66462529-7aaa5f00-eaa5-11e9-9b4f-327de4009389.png)


Regards,
Han.

**Comment by popduyhan** [comment]
Hi,

Did you find out the reason why the extension has some checkout issues?

Can you try to create some shipping methods on your side, and then choosing the different methods?
You should see the issues after doing the testing.

Thank you.

Regards,
Han.

**Comment by TekniskSupport** [comment]
No still haven't been able to reproduce the errors, works like a charm when i try.
I see you are using Apache, are you certain the htaccess-file is correct so that the requests are handled by index.php and magento is properly bootstrapped?

**Comment by popduyhan** [comment]
Hi, 

I fixed the issues on my side.

Thanks for your support.

Regards,
Han.
