### ISSUE TITLE
Svea checkout can't work if you switch the shipping methods

### ISSUE THREAD

**Issue by popduyhan** [sveawebpay/magento1-checkout#8]
To reproduce:
- In the back end: Enable some shipping methods.
- Add products to the shopping cart.
- Go to the checkout page and switch to another shipping method.

Expected result: Svea checkout loads correctly.
Actual result: Svea Checkout doesn't work.

**Comment by TekniskSupport** [comment]
We are unable to reproduce, have you contacted your Svea salesperson or handler?
They will surely help you get started, or point you in the correct direction (this is not the designated support channel)

**Comment by popduyhan** [comment]
Hi, 

I fixed the issues on my side.

Thanks for your support.

Regards,
Han.
